theme: jekyll-theme-slate
title: p5.js Templates

twitter:
  username: falworks
  card: summary_large_image
  title: p5.js Templates

defaults:
  - scope:
      path: "" # all
    values:
      image: "/images/flowchart.png"
