theme: jekyll-theme-cayman
title: p5.js Templates

twitter:
  username: falworks
  card: summary_large_image
  title: p5.js Templates

author:
  twitter: falworks

defaults:
  - scope:
      path: "" # all
    values:
      image: "/images/flowchart.png"

full_url: https://fal-works.github.io/p5js-templates
favicon: /images/favicon.ico
hide_github_button: false
